name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc-14
            cxx: g++-14
          - os: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential gcc-14 g++-14 libnghttp2-14 libnghttp2-dev libidn2-dev libidn2-0 libpsl-dev libpsl5t64
        
    - name: Configure CMake (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        export CC=${{ matrix.cc }}
        export CXX=${{ matrix.cxx }}
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        
    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
        
    - name: Build project
      run: cmake --build build --config Release
      
    - name: Run tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd build
        ./src/yahbog-tests/yahbog-tests
        
    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build
        ./src/yahbog-tests/Release/yahbog-tests.exe 