name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
            extension: ""
            subfolder: ""
          - os: windows-latest
            extension: ".exe"
            subfolder: "/Release"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential ${{ matrix.cc }} ${{ matrix.cxx }} python3 python3-pip clang
        
    - name: Configure CMake (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        export CC=${{ matrix.cc }}
        export CXX=${{ matrix.cxx }}
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        
    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
        
    - name: Build project
      run: cmake --build build --config Release
      
    - name: Get testing dependencies
      run: |
        pip install requests
        python3 scripts/get_testing_deps.py

    - name: Run tests
      run: |
        ./build/src/yahbog-tests${{ matrix.subfolder }}/yahbog-tests${{ matrix.extension }}