name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential gcc-15 g++-15
        
    - name: Configure CMake
      run: |
        export CC=gcc-15
        export CXX=g++-15
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        
    - name: Build project
      run: cmake --build build --config Release
      
    - name: Run tests
      run: |
        cd build
        ./src/yahbog-tests/yahbog-tests 